version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4201:4200"
    volumes:
      - .:/usr/src/app
    command: ["ng", "serve", "--host", "0.0.0.0"]
